language: php

php:
  - 5.3
  - 5.4

before_script:
  - pecl -q install pecl_http && echo "extension=http.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - pecl -q install gearman && echo "extension=gearman.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer --dev install

script: phpunit